export AWS_ACCESS_KEY_ID="..."
export AWS_AMI="ami-f0b11187"
export AWS_INSTANCE_TYPE="t2.micro"
export AWS_KEYPAIR_NAME="..."
export AWS_REGION="eu-west-1"
export AWS_SECRET_ACCESS_KEY="..."
export AWS_SSH_PRIVATE_KEY="..."
export AWS_SSH_USER="ubuntu"
export AWS_SUBNET_ID="..."

export ARTIFACTORY_HOST="..."
export NEXUS_HOST="..."
